problem_one/config/routes.rb
Rails.application.routes.draw do
  get 'practicing_states/index'
  get 'advocates/index'
  get 'advocates/assitants'
  get 'cases/index'
  get 'dashboard/index'
  devise_for :advocates
  devise_scope :advocate do
    get '/advocates/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'dashboard#index'

  resources :cases do
  	collection do
  		post 'take_case'
  		post 'reject_case'
  		post 'close_case'
  	end
  end

  resources :practicing_states
  resources :advocates do
  	collection do
  		post 'make_assitant'
  		post 'remove_assitant'
  		post 'add_assitant'
  		get 'new_assitant'
  		get 'assitants'
  	end
  end
end

problem_one/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  	@state_id = params[:state_id].present? ? params[:state_id] : current_advocate.filter_state_id
  	@cases = Case.new_cases.where(state_id: @state_id).paginate(page: params[:page], per_page: 10)#.where(state_id: current_advocate.practicing_states.collect(&:state_id))
  end

  def practicing
  	@cases = Case.practicing_cases.where(state_id: current_advocate.practicing_states.collect(&:state_id))
  end
end

problem_one/app/helpers/dashboard_helper.rb
module DashboardHelper
end

problem_one/app/views/dashboard/index.html.erb
<div class="container-fluid dashboard_container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<h3>New Cases</h3>
			<% if current_advocate.senior_laywer? %>
				<%= link_to "Add Case", new_case_path, class: "btn btn-primary", style: "float:left" %>
			<%end%>
			<%= select_tag :state_id, options_for_select(State.active.map{|m| [m.name,m.id]},@state_id), {prompt: "Select State", class: "form-control new_case_state", "data-url"=> dashboard_index_path , required: true, style: "float:right;width: 180px;"} %>
			<div class="col-md-12">
				<div class="table-responsive">
	      	<table class="table align-items-center table-flush">
	          <thead class="thead-light">
	          	<tr>
	    					<th>Case No.</th>
	    					<th>Case Name</th>
	    					<th>Actions</th>
	    				</tr>
	          </thead>
	          <tbody class="index_cases">
	          	<%= render "/cases/index_cases" %>
	          </tbody>
	        </table>
       	</div>
      </div>
		</div>
	</div>
</div>

<div id="caseModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Case Assignment</h4>
      </div>
      <div class="modal-body">
        <%= form_tag take_case_cases_path, method: :post, remote: true do %>
        	<%= hidden_field_tag :case_id, id: "case_id" %>
        	<div class="form-group">
        		<label>Assign To</label>
        		<%= select_tag :assign_to_id, options_for_select(current_advocate.case_assign_to.map{|a| [a.full_name,a.id]}), {class: "form-control"} %>
        	</div>
        <%end%>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

problem_one/app/views/dashboard/index.js.erb
$('.index_cases').html("<%= j(render '/cases/index_cases') %>");