problem_one/config/routes.rb
Rails.application.routes.draw do
  get 'practicing_states/index'
  get 'advocates/index'
  get 'advocates/assitants'
  get 'cases/index'
  get 'dashboard/index'
  devise_for :advocates
  devise_scope :advocate do
    get '/advocates/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'dashboard#index'

  resources :cases do
  	collection do
  		post 'take_case'
  		post 'reject_case'
  		post 'close_case'
  	end
  end

  resources :practicing_states
  resources :advocates do
  	collection do
  		post 'make_assitant'
  		post 'remove_assitant'
  		post 'add_assitant'
  		get 'new_assitant'
  		get 'assitants'
  	end
  end
end

problem_one/app/models/advocate.rb
class Advocate < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :role,optional: true
  belongs_to :honor ,optional: true, class_name: "Advocate", foreign_key: "honor_id"
  has_many :advocate_cases, class_name: "AdvocateCase", foreign_key: "advocate_id"
  has_many :assigned_cases, class_name: "AdvocateCase", foreign_key: "assign_to_id"
  has_many :assitants, class_name: "Advocate", foreign_key: "honor_id"
  has_many :practicing_states

  scope :seniors, -> {where(role_id: Role.senior_laywer.id)}
  scope :juniors, -> {where(role_id: Role.junior_laywer.id)}
  scope :new_advocates, -> {juniors.where(honor_id: nil)}

  before_save :update_role

  def update_role
  	select_role = experience.to_i > 5 ? Role.senior_laywer : Role.junior_laywer
		unless role.present?
			self.role_id = select_role.try(:id)
		end
  end

  def senior_laywer?
  	role == Role.senior_laywer
  end

  def junior_laywer?
  	role == Role.junior_laywer
  end

  def case_assign_to
  	[self] + assitants 
  end

  def filter_state_id
  	practicing_states.count > 0 ? practicing_states.last.state_id : (honor.present? ? honor.filter_state_id : State.first.id)
  end

end

problem_one/app/controllers/advocates_controller.rb
class AdvocatesController < ApplicationController
  def index
  	@advocates = Advocate.new_advocates.where.not(id: current_advocate.try(:id))
  end

  def assitants
  	@advocates = current_advocate.assitants
  end

  def make_assitant
  	@advocate = Advocate.find_by(id: params[:advocate_id])
  	@advocate.honor_id = current_advocate.id
  	@advocate.save
  	@advocates = Advocate.new_advocates.where.not(id: current_advocate.try(:id))
  end

  def remove_assitant
  	@advocate = Advocate.find_by(id: params[:advocate_id])
  	@advocate.honor_id = nil
  	@advocate.save
  	@advocate.assigned_cases.where(advocate_id: current_advocate.id).update_all(assign_to_id: current_advocate.id)
  	@advocates = Advocate.new_advocates.where.not(id: current_advocate.try(:id))
  end

  def new_assitant
  	
  end

  def add_assitant
  	@advocate = Advocate.new(advocate_params)
  	@advocate.state_id = current_advocate.state_id
  	@advocate.honor_id = current_advocate.id
  	@advocate.password = @advocate.email
  	@advocate.password_confirmation = @advocate.email
  	@advocate.save
  	redirect_to assitants_advocates_path
  end

  private

  def advocate_params
  	params.require(:advocate).permit(:full_name, :mobile, :email, :role_id, :state_id, :experience, :password, :password_confirmation)
  end
end

problem_one/app/helpers/advocates_helper.rb
module AdvocatesHelper
end

problem_one/app/views/advocates/_advocates.html.erb
<% @advocates.each.with_index(1) do |a,index| %>
	<tr class="advocate_row_<%= a.id %>">
		<td><%= index %></td>
		<td><%= a.full_name %></td>
		<td><%= "#{a.experience} Year".pluralize(a.experience.to_i) %></td>
		<td>
			<% if current_advocate.senior_laywer? %>
				<% if a.honor_id.present? %>
					<%= link_to "Remove assitant", "javascript:void(0)", 'data-advocate'=> a.id, 'data-url'=>remove_assitant_advocates_path , class: "btn btn-primary remove_assitant" %>
				<%else%>
					<%= link_to "Make assitant", "javascript:void(0)", 'data-advocate'=> a.id, 'data-url'=>make_assitant_advocates_path , class: "btn btn-primary make_assitant" %>
				<%end%>
			<%end%>
		</td>
	</tr>
<%end%>

problem_one/app/views/advocates/assitants.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<h3>Assitants</h3>
			 <div class="table-responsive">
      	<table class="table align-items-center table-flush">
          <thead class="thead-light">
          	<tr>
    					<th>S.No.</th>
    					<th>Advocate Name</th>
    					<th>Experience</th>
    					<th>Action</th>
    				</tr>
          </thead>
          <tbody class="advocate_lists">
          	<%= render "/advocates/advocates" %>
          </tbody>
        </table>
       </div>
		</div>
	</div>
</div>

problem_one/app/views/advocates/index.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<h3>New Advocates</h3>
			<%= link_to "Add Advocate", new_assitant_advocates_path, class: "btn btn-primary" %>
			 <div class="table-responsive">
      	<table class="table align-items-center table-flush">
          <thead class="thead-light">
          	<tr>
    					<th>S.No.</th>
    					<th>Advocate Name</th>
    					<th>Experience</th>
    					<th>Action</th>
    				</tr>
          </thead>
          <tbody class="advocate_lists">
          	<%= render "/advocates/advocates" %>
          </tbody>
        </table>
       </div>
		</div>
	</div>
</div>

problem_one/app/views/advocates/make_assitant.js.erb
<% if @advocate.errors.any? %>
	alert("<%= @advocate.errors.full_messages.join(',') %>");
<%else%>
	$('.advocate_row_<%= @advocate.id %>').remove();
	$('.advocate_lists').html("<%= j(render '/advocates/advocates') %>");
<%end%>

problem_one/app/views/advocates/new_assitant.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2>Add Assitant</h2>

  <%= form_for :advocate, url: add_assitant_advocates_path do |f| %>

    <div class="form-group">
      <%= f.label :full_name %><br />
      <%= f.text_field :full_name , class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= f.label :mobile %><br />
      <%= f.text_field :mobile , class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control", required: true %>
      <span class="sm_notes">You can use the same email address as your password for the login. You can change the password in edit profile section.</span>
    </div>

    <div class="form-group">
      <%= f.label :experience %><br />
      <%= f.select :experience, options_for_select((1..5).map{|m| [("#{m} year").pluralize(m) ,m] }), {prompt: "Select Experience"} , {class: "form-control", required: true} %>
    </div>

    <div class="form-group hide">
      <%= f.label :password %>
      <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <%= f.password_field :password, autocomplete: "new-password", class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= f.submit "Advocate", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>