problem_one/config/routes.rb
Rails.application.routes.draw do
  get 'practicing_states/index'
  get 'advocates/index'
  get 'advocates/assitants'
  get 'cases/index'
  get 'dashboard/index'
  devise_for :advocates
  devise_scope :advocate do
    get '/advocates/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'dashboard#index'

  resources :cases do
  	collection do
  		post 'take_case'
  		post 'reject_case'
  		post 'close_case'
  	end
  end

  resources :practicing_states
  resources :advocates do
  	collection do
  		post 'make_assitant'
  		post 'remove_assitant'
  		post 'add_assitant'
  		get 'new_assitant'
  		get 'assitants'
  	end
  end
end

problem_one/app/controllers/cases_controller.rb
class CasesController < ApplicationController
  before_action :get_case, only: [:take_case]

  def index
  	if current_advocate.senior_laywer?
	  	@cases = AdvocateCase.where(advocate_id: current_advocate.id)
	  elsif current_advocate.junior_laywer?
	  	@cases = AdvocateCase.where(assign_to_id: current_advocate.id)
	  	# @cases = current_advocate.assigned_cases.where(case_status_id: CaseStatus.try(:practicing_case).try(:id))
	  end
  end

  def take_case
  	@advocate_case = current_advocate.advocate_cases.find_or_initialize_by(case_id: @case.id) if current_advocate.senior_laywer?.present?
  	if current_advocate.junior_laywer?.present?
	  	@advocate_case = current_advocate.assigned_cases.build(case_id: @case.id) 
	  	@advocate_case.advocate_id = current_advocate.honor_id 
	  end
  	@advocate_case.case_status_id = CaseStatus.practicing_case.id
  	@advocate_case.assign_to_id = params[:assign_to_id]
  	@advocate_case.save
  	get_cases
  end

  def show
  	@case = Case.find_by(id: params[:id])
  	@reject_case = current_advocate.advocate_cases.find_by(case_id: @case.id).try(:case_status) == CaseStatus.reject_case
  end

  def close_case
  	@advocate_case =AdvocateCase.find_by(id: params[:case_id])
  	@advocate_case.case_status_id = CaseStatus.close_case.id
  	@advocate_case.save
  end

  def create
  	@errors = []
  	@case = Case.new(case_params)
  	@case.case_status_id = CaseStatus.new_case.try(:id)
  	valid = current_advocate.practicing_states.collect(&:state_id).include?(@case.state_id)
  	if valid.present?
	  	if @case.save
	  		take_case
	  	end
	  else
	  	@errors << "Your not eligible to take or create this state case"
	  end
  end

  def reject_case
  	@case = Case.find_by(id: params[:case_id])
  	@advocate_case = current_advocate.advocate_cases.build(case_id: @case.id)
  	@advocate_case.case_status_id = CaseStatus.reject_case.id
  	@advocate_case.save
  end

  private

  def get_case
  	@case = Case.find_by(id: params[:case_id])
  end

  def get_cases
  	@cases = Case.new_cases.where(state_id: current_advocate.state_id)
  end

  def case_params
  	params.require(:case).permit(:case_no, :name, :description,:state_id)
  end
end

problem_one/app/helpers/cases_helper.rb
module CasesHelper
end

problem_one/app/views/cases/_cases.html.erb
<% @cases.each do |c| %>
	<tr class="row_<%= c.id %>">
		<td><%= c.try(:case).case_no %></td>
		<td><%= c.try(:case).name %></td>
		<td><%= c.try(:case_status).try(:name) %></td>
		<td><%= c.try(:assign_laywer).try(:full_name) %></td>
		<td>
			<% if current_advocate.senior_laywer? && c.try(:case_status).try(:practicing_case?) %>
				<%= link_to "Close Case", "javascript:void(0);", "data-url"=>close_case_cases_path, "data-case"=>c.id, data: {confirm: "Are you sure?"} , class: "btn btn-primary close_case" %>
			<%else%>
				-
			<%end%>
		</td>
	</tr>
<%end%>

problem_one/app/views/cases/_index_cases.html.erb
<% @cases.each do |c| %>
	<tr class="row_<%= c.id %>">
		<td><%= c.case_no %></td>
		<td><%= c.name %></td>
		<td>
			<%= link_to "Show", case_path(c), class: "btn btn-primary" %>
			<% if current_advocate.senior_laywer? %>
				<%= link_to "Reject", "javascript:void(0);", "data-url"=> reject_case_cases_path, "data-case"=>c.id , data: {confirm: "Are you sure?"}, class: "btn btn-danger reject_case" %>
			<%end%>
		</td>
	</tr>
<%end%>

<%= will_paginate @cases, renderer: BootstrapPagination::Rails %>

problem_one/app/views/cases/close_case.js.erb
<% if @advocate_case.errors.any? %>
	alert("<%= @advocate_case.errors.full_messages.join(',') %>");
<%else%>
	location.assign("<%= cases_path %>");
<%end%>

problem_one/app/views/cases/create.js.erb
<% if @errors.any? %>
		alert("<%= @errors.join(',') %>");
<%else%>
	<% if @case.errors.any? %>
		alert("<%= @case.errors.full_messages.join(',') %>");
	<%else%>
		// $('.row_<%#= @case.id %>').remove();
		// $('.advocate_cases').html("<%#= j(render '/cases/cases') %>");
		location.assign("<%= cases_path %>");
	<%end%>
<%end%>

problem_one/app/views/cases/index.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<h3>Practicing Cases</h3>
      <% if current_advocate.senior_laywer? %>
        <%= link_to "Add Case", new_case_path, class: "btn btn-primary" %>
      <%end%>
			 <div class="table-responsive">
      	<table class="table align-items-center table-flush">
          <thead class="thead-light">
          	<tr>
    					<th>Case No.</th>
    					<th>Case Name</th>
              <th>Case Status</th>
              <th>Assign To</th>
    					<th>Actions</th>
    				</tr>
          </thead>
          <tbody class="advocate_cases">
          	<%= render "/cases/cases" %>
          </tbody>
        </table>
       </div>
		</div>
	</div>
</div>

problem_one/app/views/cases/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2>Add Case</h2>

  <%= form_for :case, url: cases_path, method: :post, remote: true do |f| %>

    <div class="form-group">
      <%= f.label :case_no %><br />
      <%= f.text_field :case_no , class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= f.label :name %><br />
      <%= f.text_field :name , class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= f.label :description %><br />
      <%= f.text_area :description, class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= f.label :state %><br />
      <%= f.select :state_id, options_for_select(State.active.map{|m| [m.name,m.id]}), {prompt: "Select State"} , {class: "form-control", required: true} %>
    </div>

    <div class="form-group">
      <%= f.label :assign_to %><br />
      <%= select_tag :assign_to_id, options_for_select(current_advocate.case_assign_to.map{|a| [a.full_name,a.id]}), {class: "form-control"} %>
    </div>

    <div class="form-group">
      <%= f.submit "Create", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

problem_one/app/views/cases/reject_case.js.erb
<% if @advocate_case.errors.any? %>
		alert("<%= @advocate_case.errors.full_messages.join(',') %>");
<%else%>
	<% if @case.errors.any? %>
		alert("<%= @case.errors.full_messages.join(',') %>");
	<%else%>
		// $('.row_<%#= @case.id %>').remove();
		// $('.advocate_cases').html("<%#= j(render '/cases/cases') %>");
		location.assign("<%= cases_path %>");
	<%end%>
<%end%>

problem_one/app/views/cases/show.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<h3>Practicing Cases</h3>
			 <div class="table-responsive">
      	<table class="table align-items-center table-flush">
          <thead class="thead-light">
          	<tr>
    					<th width="20%">Case No.</th>
    					<th width="20%">Case Name</th>
    					<th width="60%">Description</th>
    				</tr>
          </thead>
          <tbody class="">
            <tr class="row_<%= @case.id %>">
              <td><%= @case.case_no %></td>
              <td><%= @case.name %></td>
              <td>
                <%= @case.description %>
              </td>
            </tr>
          </tbody>
        </table>
       </div>
       <div class="table-responsive">
        <% if current_advocate.senior_laywer? %>
          <%= form_tag take_case_cases_path, method: :post, remote: true do %>
            <%= hidden_field_tag :case_id, @case.id , id: "case_id" %>
            <div class="form-group">
              <label>Assign To</label>
              <%= select_tag :assign_to_id, options_for_select(current_advocate.case_assign_to.map{|a| [a.full_name,a.id]}), {class: "form-control"} %>
            </div>
            <div class="form-group">
              <% if @reject_case %>
                <button type="submit" data-confirm="As you already rejected the case are you willing to remove from reject list and assign this case." class="btn btn-primary">Assign</button>
              <%else%>
                <button type="submit" class="btn btn-primary">Assign</button>
              <%end%>
            </div>
          <%end%>
        <% elsif current_advocate.junior_laywer? %>
          <%= form_tag take_case_cases_path, method: :post, remote: true do %>
            <%= hidden_field_tag :case_id, @case.id , id: "case_id" %>
            <%= hidden_field_tag :assign_to_id, current_advocate.id %>
            <div class="form-group">
              <button type="submit" class="btn btn-primary">Take the case</button>
            </div>
          <%end%>
        <%end%>
      </div>
		</div>
	</div>
</div>

problem_one/app/views/cases/take_case.js.erb
<% if @advocate_case.errors.any? %>
	alert("<%= @advocate_case.errors.full_messages.join(',') %>");
<%else%>
	// $('.row_<%#= @case.id %>').remove();
	// $('.advocate_cases').html("<%#= j(render '/cases/cases') %>");
	location.assign("<%= cases_path %>")
<%end%>